### ISSUE TITLE
Demonstration

### ISSUE THREAD

**Issue by janstieler** [Frogmouth/jQuery.Wishlist#1]
Hi,
I would appreciate if you could add an demonstration of your wishlist plugin.

Best regrads

**Comment by Frogmouth** [comment]
Hi,
i'm so sorry, but, right now i can't create a demostration because I have no time to do that. My work brings away all of my time (even the freetime :( )... however I'm glad to see that someone is interested of my work, so, for you I try to build an online demostration of my plugin, but, no promise for when.

**Comment by johnnydevs** [comment]
I would also like this +1 Looks like a good plugin thanks

**Comment by Frogmouth** [comment]
hi guys,
unfortunately I'm working a lot and I have little time. The plugin is immature but in the Christmas holidays I will work in a demo. I hope to finish it within a few days.

;)

**Comment by Frogmouth** [comment]
An example :8ball: 
https://github.com/Frogmouth/jQuery.Wishlist/tree/master/examples

**Comment by johnnydevs** [comment]
Thanks for this @Frogmouth it works really well and is a great starting point for what I want to achieve! Hopefully I can build on this to suit my needs. I have some ideas in mind.

**Comment by Frogmouth** [comment]
If you need something else, tell me. Also about your **ideas**. Right now this plugin is useless for me, I develop it only for my pleasure some case histories could be useful.
