### ISSUE TITLE
How to remove an item from within the wishbar

### ISSUE THREAD

**Issue by aottenp** [Frogmouth/jQuery.Wishlist#4]
Hello Simone,
First of all, I realy like this script.
I'm filling the Wishbar from different pages. So it's not easy to delete one item.
Is it possible to delete an item from within the wishbar.

Thanks

**Comment by Frogmouth** [comment]
Hi mate!
You can do this, but not with default plugin. You need to change the core plugin script.
This a quick answer to help you, so when a have more time i can update my project to add this features.
take **jquery-wishlist.js**:
1. Remove the line since:
   
   ```
   94:     $(this).on(settings.triggerEvent + ".wish","."+settings.triggerClass, function(event){
   [...]
   105:    });
   ```
2. and add this handler, before the `return` inside line `91`
   
   ```
   $(document).on(settings.triggerEvent + ".wish","."+settings.triggerClass, function(event){
           event.preventDefault();
           var data = picker($(this));
   
           if($(this).hasClass(settings.addClass)){
               WISHLIST.addToWish(data);
               if(settings.addClass) $(this).removeClass(settings.addClass).addClass(settings.removeClass);
           }else{
               WISHLIST.removeToWish(data.id);
               if(settings.addClass) $(this).removeClass(settings.removeClass).addClass(settings.addClass);
           }
       });
   ```
   
   this a generic handler for manage the `remove` also in wishbar.
3. inside the function: `var itemList` at current line: `126` add this line:
   `data.wid = WISHLIST.ID;`
4. When you initialize the Wishlist, add the option `barOption->template`, like:
   
   ```
   window.MYwishlist = $.Wishlist("wishlist",{
               barOption : {
                   template : "<div rel='<%- wid %>' id='wishItem_<%- id %>' class='wishedItem' data-id='<%- id %>'><img src='<%- img %>'><p><%- title %></p><a class='wishAction removeToWish' data-id='<%- id %>' href='<%- id %>'></a></div>"
               }
           });
   ```
   
   Note: `rel='<%- wid %>'` (dynamic wishlist ID) and `<a class='wishAction removeToWish' data-id='<%- id %>' href='<%- id %>'></a>` (add Remove Button to wishbar item template).

Tell me if u has some problem.
Thx Mate!

**Comment by aottenp** [comment]
Hi Simone,
Thank you for your quick response. It's working great.

I have another question: Can I set a Maximum number for items in the wishbar? 

Thanks

**Comment by Frogmouth** [comment]
Yes, you can, but rightnow like the other request isn't a feature of wishlist.
But, you can do it yourelf:
1. Open jquery-wishlist.js
2. Find this line: `WISHLIST.addToWish = function(data){` and add this line before all code inside function:
   
   ```
   if(WISHLIST.data.length >= ##NUMBER##) return false;
   ```
3. Replece **##NUMBER##** with the max number of elements

Right now only returns the variable and does nothing. Maybe is better if you call a function or a custom method to alert the user that he reached the maximum number of items in wishlist.

Like: 

```
if(WISHLIST.data.length >= 10) return alert("Sorry, you already have 10 items inside your wishlist. Deletes one before.");
```

Enjoy.
